[build]
  publish = "src/graphdeck/web"
  command = ""   # no build step

# Optional: keep the UI fresh in the browser
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma        = "no-cache"
    Expires       = "0"

